apiVersion: v1
kind: Pod
metadata:
  labels:
    run: probe
  name: probe
spec:
  containers:
  - image: httpd
    name: probe
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
